apiVersion: apps/v1
kind: Deployment
metadata:
  name: career-mentor-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: career-mentor-backend
  template:
    metadata:
      labels:
        app: career-mentor-backend
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          image: limemanas/career-mentor-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: API_URL
              value: "http://career-mentor-backend:8000"
            - name: OLLAMA_HOST
              value: "http://ollama:11434"   
---
apiVersion: v1
kind: Service
metadata:
  name: career-mentor-backend
spec:
  selector:
    app: career-mentor-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
