name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Free up disk space BEFORE building
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./app/backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ai-career-mentor-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/ai-career-mentor-backend:${{ github.sha }}
          platforms: linux/amd64

      # Build and Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./app/frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ai-career-mentor-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/ai-career-mentor-frontend:${{ github.sha }}
          platforms: linux/amd64

      # Set up Minikube
      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: 1.32.0
          kubernetes-version: 1.28.3

      # Ensure Tavily secret exists
      - name: Create/Update Tavily Secret
        run: |
          kubectl delete secret tavily-secret --ignore-not-found
          kubectl create secret generic tavily-secret --from-literal=TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/frontend-deployment.yaml

      # Debugging: Get pod status and logs if rollout fails
      - name: Get pod status and logs if rollout fails
        if: failure()
        run: |
          kubectl get pods -A
          kubectl describe deployment career-mentor-backend
          kubectl logs $(kubectl get pods -l app=career-mentor-backend -o jsonpath="{.items[0].metadata.name}")
