# Solution 1: Updated CI/CD with Space Management
name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Free up disk space BEFORE building
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      # Additional manual cleanup
      - name: Clean up system
        run: |
          # Remove unnecessary packages
          sudo apt-get clean
          sudo apt-get autoremove -y
          
          # Clear Docker cache
          docker system prune -af --volumes
          
          # Show available space
          df -h
          echo "Available disk space after cleanup:"
          df -h /

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Set up Docker Buildx with limited cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:buildx-stable-1
            network=host

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build backend with optimized settings
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./app/backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ai-career-mentor-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/ai-career-mentor-backend:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min  # Reduced cache to save space
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      # Clean up between builds
      - name: Clean Docker cache between builds
        run: |
          docker system prune -f
          df -h

      # Build frontend with optimized settings
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./app/frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ai-career-mentor-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/ai-career-mentor-frontend:${{ github.sha }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=min
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      # Rest of your deployment steps...
      - name: Set up Minikube
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: 1.32.0
          kubernetes-version: 1.28.3

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/career-mentor-backend --timeout=1000s
          kubectl rollout status deployment/career-mentor-frontend --timeout=1000s

      # Final cleanup
      - name: Final cleanup
        if: always()
        run: |
          docker system prune -af --volumes
          df -h
